/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTanchatRouteImport } from './routes/demo/tanchat'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as AgentSettingsRouteImport } from './routes/agent/settings'
import { Route as AgentDashboardRouteImport } from './routes/agent/dashboard'
import { Route as SuperAdminClientsIndexRouteImport } from './routes/super-admin/clients/index'
import { Route as ExampleGuitarsIndexRouteImport } from './routes/example.guitars/index'
import { Route as AgentAppointmentsIndexRouteImport } from './routes/agent/appointments/index'
import { Route as AdminLeadsIndexRouteImport } from './routes/admin/leads/index'
import { Route as AdminCampaignsIndexRouteImport } from './routes/admin/campaigns/index'
import { Route as AdminAgentsIndexRouteImport } from './routes/admin/agents/index'
import { Route as SuperAdminClientsCreateRouteImport } from './routes/super-admin/clients/create'
import { Route as ExampleGuitarsGuitarIdRouteImport } from './routes/example.guitars/$guitarId'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiTanchatRouteImport } from './routes/demo/api.tanchat'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as SuperAdminClientsClientIdIndexRouteImport } from './routes/super-admin/clients/$clientId/index'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as SuperAdminClientsClientIdEditRouteImport } from './routes/super-admin/clients/$clientId/edit'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanchatRoute = DemoTanchatRouteImport.update({
  id: '/demo/tanchat',
  path: '/demo/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSettingsRoute = AgentSettingsRouteImport.update({
  id: '/agent/settings',
  path: '/agent/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/agent/dashboard',
  path: '/agent/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminClientsIndexRoute = SuperAdminClientsIndexRouteImport.update({
  id: '/super-admin/clients/',
  path: '/super-admin/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleGuitarsIndexRoute = ExampleGuitarsIndexRouteImport.update({
  id: '/example/guitars/',
  path: '/example/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAppointmentsIndexRoute = AgentAppointmentsIndexRouteImport.update({
  id: '/agent/appointments/',
  path: '/agent/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsIndexRoute = AdminLeadsIndexRouteImport.update({
  id: '/admin/leads/',
  path: '/admin/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampaignsIndexRoute = AdminCampaignsIndexRouteImport.update({
  id: '/admin/campaigns/',
  path: '/admin/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsIndexRoute = AdminAgentsIndexRouteImport.update({
  id: '/admin/agents/',
  path: '/admin/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminClientsCreateRoute = SuperAdminClientsCreateRouteImport.update({
  id: '/super-admin/clients/create',
  path: '/super-admin/clients/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleGuitarsGuitarIdRoute = ExampleGuitarsGuitarIdRouteImport.update({
  id: '/example/guitars/$guitarId',
  path: '/example/guitars/$guitarId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTanchatRoute = DemoApiTanchatRouteImport.update({
  id: '/demo/api/tanchat',
  path: '/demo/api/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminClientsClientIdIndexRoute =
  SuperAdminClientsClientIdIndexRouteImport.update({
    id: '/super-admin/clients/$clientId/',
    path: '/super-admin/clients/$clientId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminClientsClientIdEditRoute =
  SuperAdminClientsClientIdEditRouteImport.update({
    id: '/super-admin/clients/$clientId/edit',
    path: '/super-admin/clients/$clientId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/settings': typeof AgentSettingsRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanchat': typeof DemoTanchatRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tanchat': typeof DemoApiTanchatRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/super-admin/clients/create': typeof SuperAdminClientsCreateRoute
  '/admin/agents': typeof AdminAgentsIndexRoute
  '/admin/campaigns': typeof AdminCampaignsIndexRoute
  '/admin/leads': typeof AdminLeadsIndexRoute
  '/agent/appointments': typeof AgentAppointmentsIndexRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
  '/super-admin/clients': typeof SuperAdminClientsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/super-admin/clients/$clientId/edit': typeof SuperAdminClientsClientIdEditRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/super-admin/clients/$clientId': typeof SuperAdminClientsClientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/settings': typeof AgentSettingsRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanchat': typeof DemoTanchatRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tanchat': typeof DemoApiTanchatRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/super-admin/clients/create': typeof SuperAdminClientsCreateRoute
  '/admin/agents': typeof AdminAgentsIndexRoute
  '/admin/campaigns': typeof AdminCampaignsIndexRoute
  '/admin/leads': typeof AdminLeadsIndexRoute
  '/agent/appointments': typeof AgentAppointmentsIndexRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
  '/super-admin/clients': typeof SuperAdminClientsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/super-admin/clients/$clientId/edit': typeof SuperAdminClientsClientIdEditRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/super-admin/clients/$clientId': typeof SuperAdminClientsClientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/settings': typeof AgentSettingsRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanchat': typeof DemoTanchatRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tanchat': typeof DemoApiTanchatRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/super-admin/clients/create': typeof SuperAdminClientsCreateRoute
  '/admin/agents/': typeof AdminAgentsIndexRoute
  '/admin/campaigns/': typeof AdminCampaignsIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
  '/agent/appointments/': typeof AgentAppointmentsIndexRoute
  '/example/guitars/': typeof ExampleGuitarsIndexRoute
  '/super-admin/clients/': typeof SuperAdminClientsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/super-admin/clients/$clientId/edit': typeof SuperAdminClientsClientIdEditRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/super-admin/clients/$clientId/': typeof SuperAdminClientsClientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent/dashboard'
    | '/agent/settings'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanchat'
    | '/demo/tanstack-query'
    | '/demo/api/names'
    | '/demo/api/tanchat'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/super-admin/clients/create'
    | '/admin/agents'
    | '/admin/campaigns'
    | '/admin/leads'
    | '/agent/appointments'
    | '/example/guitars'
    | '/super-admin/clients'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/super-admin/clients/$clientId/edit'
    | '/demo/start/ssr'
    | '/super-admin/clients/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent/dashboard'
    | '/agent/settings'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanchat'
    | '/demo/tanstack-query'
    | '/demo/api/names'
    | '/demo/api/tanchat'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/super-admin/clients/create'
    | '/admin/agents'
    | '/admin/campaigns'
    | '/admin/leads'
    | '/agent/appointments'
    | '/example/guitars'
    | '/super-admin/clients'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/super-admin/clients/$clientId/edit'
    | '/demo/start/ssr'
    | '/super-admin/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/agent/dashboard'
    | '/agent/settings'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanchat'
    | '/demo/tanstack-query'
    | '/demo/api/names'
    | '/demo/api/tanchat'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/super-admin/clients/create'
    | '/admin/agents/'
    | '/admin/campaigns/'
    | '/admin/leads/'
    | '/agent/appointments/'
    | '/example/guitars/'
    | '/super-admin/clients/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/super-admin/clients/$clientId/edit'
    | '/demo/start/ssr/'
    | '/super-admin/clients/$clientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentDashboardRoute: typeof AgentDashboardRoute
  AgentSettingsRoute: typeof AgentSettingsRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanchatRoute: typeof DemoTanchatRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTanchatRoute: typeof DemoApiTanchatRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ExampleGuitarsGuitarIdRoute: typeof ExampleGuitarsGuitarIdRoute
  SuperAdminClientsCreateRoute: typeof SuperAdminClientsCreateRoute
  AdminAgentsIndexRoute: typeof AdminAgentsIndexRoute
  AdminCampaignsIndexRoute: typeof AdminCampaignsIndexRoute
  AdminLeadsIndexRoute: typeof AdminLeadsIndexRoute
  AgentAppointmentsIndexRoute: typeof AgentAppointmentsIndexRoute
  ExampleGuitarsIndexRoute: typeof ExampleGuitarsIndexRoute
  SuperAdminClientsIndexRoute: typeof SuperAdminClientsIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  SuperAdminClientsClientIdEditRoute: typeof SuperAdminClientsClientIdEditRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
  SuperAdminClientsClientIdIndexRoute: typeof SuperAdminClientsClientIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanchat': {
      id: '/demo/tanchat'
      path: '/demo/tanchat'
      fullPath: '/demo/tanchat'
      preLoaderRoute: typeof DemoTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/settings': {
      id: '/agent/settings'
      path: '/agent/settings'
      fullPath: '/agent/settings'
      preLoaderRoute: typeof AgentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/dashboard': {
      id: '/agent/dashboard'
      path: '/agent/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/clients/': {
      id: '/super-admin/clients/'
      path: '/super-admin/clients'
      fullPath: '/super-admin/clients'
      preLoaderRoute: typeof SuperAdminClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/guitars/': {
      id: '/example/guitars/'
      path: '/example/guitars'
      fullPath: '/example/guitars'
      preLoaderRoute: typeof ExampleGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/appointments/': {
      id: '/agent/appointments/'
      path: '/agent/appointments'
      fullPath: '/agent/appointments'
      preLoaderRoute: typeof AgentAppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads/': {
      id: '/admin/leads/'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campaigns/': {
      id: '/admin/campaigns/'
      path: '/admin/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents/': {
      id: '/admin/agents/'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/clients/create': {
      id: '/super-admin/clients/create'
      path: '/super-admin/clients/create'
      fullPath: '/super-admin/clients/create'
      preLoaderRoute: typeof SuperAdminClientsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/guitars/$guitarId': {
      id: '/example/guitars/$guitarId'
      path: '/example/guitars/$guitarId'
      fullPath: '/example/guitars/$guitarId'
      preLoaderRoute: typeof ExampleGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tanchat': {
      id: '/demo/api/tanchat'
      path: '/demo/api/tanchat'
      fullPath: '/demo/api/tanchat'
      preLoaderRoute: typeof DemoApiTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/clients/$clientId/': {
      id: '/super-admin/clients/$clientId/'
      path: '/super-admin/clients/$clientId'
      fullPath: '/super-admin/clients/$clientId'
      preLoaderRoute: typeof SuperAdminClientsClientIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/clients/$clientId/edit': {
      id: '/super-admin/clients/$clientId/edit'
      path: '/super-admin/clients/$clientId/edit'
      fullPath: '/super-admin/clients/$clientId/edit'
      preLoaderRoute: typeof SuperAdminClientsClientIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentDashboardRoute: AgentDashboardRoute,
  AgentSettingsRoute: AgentSettingsRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanchatRoute: DemoTanchatRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTanchatRoute: DemoApiTanchatRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ExampleGuitarsGuitarIdRoute: ExampleGuitarsGuitarIdRoute,
  SuperAdminClientsCreateRoute: SuperAdminClientsCreateRoute,
  AdminAgentsIndexRoute: AdminAgentsIndexRoute,
  AdminCampaignsIndexRoute: AdminCampaignsIndexRoute,
  AdminLeadsIndexRoute: AdminLeadsIndexRoute,
  AgentAppointmentsIndexRoute: AgentAppointmentsIndexRoute,
  ExampleGuitarsIndexRoute: ExampleGuitarsIndexRoute,
  SuperAdminClientsIndexRoute: SuperAdminClientsIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  SuperAdminClientsClientIdEditRoute: SuperAdminClientsClientIdEditRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
  SuperAdminClientsClientIdIndexRoute: SuperAdminClientsClientIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
