/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardRecordingsRouteImport } from './routes/dashboard/recordings'
import { Route as DashboardLogsRouteImport } from './routes/dashboard/logs'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard/leads'
import { Route as DashboardGsmDevicesRouteImport } from './routes/dashboard/gsm-devices'
import { Route as DashboardCampaignsRouteImport } from './routes/dashboard/campaigns'
import { Route as DashboardClientsIndexRouteImport } from './routes/dashboard/clients/index'
import { Route as DashboardClientsCreateRouteImport } from './routes/dashboard/clients/create'
import { Route as DashboardClientsClientIdIndexRouteImport } from './routes/dashboard/clients/$clientId/index'
import { Route as DashboardClientsClientIdEditRouteImport } from './routes/dashboard/clients/$clientId/edit'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecordingsRoute = DashboardRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGsmDevicesRoute = DashboardGsmDevicesRouteImport.update({
  id: '/gsm-devices',
  path: '/gsm-devices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsRoute = DashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsCreateRoute = DashboardClientsCreateRouteImport.update({
  id: '/clients/create',
  path: '/clients/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsClientIdIndexRoute =
  DashboardClientsClientIdIndexRouteImport.update({
    id: '/clients/$clientId/',
    path: '/clients/$clientId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardClientsClientIdEditRoute =
  DashboardClientsClientIdEditRouteImport.update({
    id: '/clients/$clientId/edit',
    path: '/clients/$clientId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/gsm-devices': typeof DashboardGsmDevicesRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/recordings': typeof DashboardRecordingsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/create': typeof DashboardClientsCreateRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
  '/dashboard/clients/$clientId/edit': typeof DashboardClientsClientIdEditRoute
  '/dashboard/clients/$clientId': typeof DashboardClientsClientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/gsm-devices': typeof DashboardGsmDevicesRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/recordings': typeof DashboardRecordingsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/clients/create': typeof DashboardClientsCreateRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
  '/dashboard/clients/$clientId/edit': typeof DashboardClientsClientIdEditRoute
  '/dashboard/clients/$clientId': typeof DashboardClientsClientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/gsm-devices': typeof DashboardGsmDevicesRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/recordings': typeof DashboardRecordingsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/create': typeof DashboardClientsCreateRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/clients/$clientId/edit': typeof DashboardClientsClientIdEditRoute
  '/dashboard/clients/$clientId/': typeof DashboardClientsClientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/verify'
    | '/dashboard/campaigns'
    | '/dashboard/gsm-devices'
    | '/dashboard/leads'
    | '/dashboard/logs'
    | '/dashboard/recordings'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/clients/create'
    | '/dashboard/clients'
    | '/dashboard/clients/$clientId/edit'
    | '/dashboard/clients/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/verify'
    | '/dashboard/campaigns'
    | '/dashboard/gsm-devices'
    | '/dashboard/leads'
    | '/dashboard/logs'
    | '/dashboard/recordings'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/clients/create'
    | '/dashboard/clients'
    | '/dashboard/clients/$clientId/edit'
    | '/dashboard/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/verify'
    | '/dashboard/campaigns'
    | '/dashboard/gsm-devices'
    | '/dashboard/leads'
    | '/dashboard/logs'
    | '/dashboard/recordings'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/clients/create'
    | '/dashboard/clients/'
    | '/dashboard/clients/$clientId/edit'
    | '/dashboard/clients/$clientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recordings': {
      id: '/dashboard/recordings'
      path: '/recordings'
      fullPath: '/dashboard/recordings'
      preLoaderRoute: typeof DashboardRecordingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gsm-devices': {
      id: '/dashboard/gsm-devices'
      path: '/gsm-devices'
      fullPath: '/dashboard/gsm-devices'
      preLoaderRoute: typeof DashboardGsmDevicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns': {
      id: '/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof DashboardCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/': {
      id: '/dashboard/clients/'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/create': {
      id: '/dashboard/clients/create'
      path: '/clients/create'
      fullPath: '/dashboard/clients/create'
      preLoaderRoute: typeof DashboardClientsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/$clientId/': {
      id: '/dashboard/clients/$clientId/'
      path: '/clients/$clientId'
      fullPath: '/dashboard/clients/$clientId'
      preLoaderRoute: typeof DashboardClientsClientIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/$clientId/edit': {
      id: '/dashboard/clients/$clientId/edit'
      path: '/clients/$clientId/edit'
      fullPath: '/dashboard/clients/$clientId/edit'
      preLoaderRoute: typeof DashboardClientsClientIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCampaignsRoute: typeof DashboardCampaignsRoute
  DashboardGsmDevicesRoute: typeof DashboardGsmDevicesRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardRecordingsRoute: typeof DashboardRecordingsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClientsCreateRoute: typeof DashboardClientsCreateRoute
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
  DashboardClientsClientIdEditRoute: typeof DashboardClientsClientIdEditRoute
  DashboardClientsClientIdIndexRoute: typeof DashboardClientsClientIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCampaignsRoute: DashboardCampaignsRoute,
  DashboardGsmDevicesRoute: DashboardGsmDevicesRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardRecordingsRoute: DashboardRecordingsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClientsCreateRoute: DashboardClientsCreateRoute,
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
  DashboardClientsClientIdEditRoute: DashboardClientsClientIdEditRoute,
  DashboardClientsClientIdIndexRoute: DashboardClientsClientIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
