/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardMonitoringRouteImport } from './routes/dashboard/monitoring'
import { Route as DashboardLogsRouteImport } from './routes/dashboard/logs'
import { Route as DashboardBroadcastRouteImport } from './routes/dashboard/broadcast'
import { Route as DashboardWhatsappIndexRouteImport } from './routes/dashboard/whatsapp/index'
import { Route as DashboardSipExtensionsIndexRouteImport } from './routes/dashboard/sip-extensions/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardLeadsIndexRouteImport } from './routes/dashboard/leads/index'
import { Route as DashboardInternalUserIndexRouteImport } from './routes/dashboard/internal-user/index'
import { Route as DashboardGsmDevicesIndexRouteImport } from './routes/dashboard/gsm-devices/index'
import { Route as DashboardClientsIndexRouteImport } from './routes/dashboard/clients/index'
import { Route as DashboardCampaignsIndexRouteImport } from './routes/dashboard/campaigns/index'
import { Route as DashboardGsmDevicesGsmDeviceIdRouteImport } from './routes/dashboard/gsm-devices/$gsmDeviceId'
import { Route as DashboardClientsCreateRouteImport } from './routes/dashboard/clients/create'
import { Route as DashboardSettingsMobileOperatorIndexRouteImport } from './routes/dashboard/settings/mobile-operator/index'
import { Route as DashboardSettingsLayoutIndexRouteImport } from './routes/dashboard/settings/layout/index'
import { Route as DashboardSettingsDefaultPricingIndexRouteImport } from './routes/dashboard/settings/default-pricing/index'
import { Route as DashboardSettingsAiProviderIndexRouteImport } from './routes/dashboard/settings/ai-provider/index'
import { Route as DashboardClientsClientIdIndexRouteImport } from './routes/dashboard/clients/$clientId/index'
import { Route as DashboardCampaignsCampaignIdIndexRouteImport } from './routes/dashboard/campaigns/$campaignId/index'
import { Route as DashboardWhatsappSettingIdRouteImport } from './routes/dashboard/whatsapp/setting.$id'
import { Route as DashboardWhatsappDetailsInstanceIdRouteImport } from './routes/dashboard/whatsapp/details.$instanceId'
import { Route as DashboardClientsClientIdEditRouteImport } from './routes/dashboard/clients/$clientId/edit'
import { Route as DashboardCampaignsCampaignIdAnalyticRouteImport } from './routes/dashboard/campaigns/$campaignId/analytic'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitoringRoute = DashboardMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBroadcastRoute = DashboardBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatsappIndexRoute = DashboardWhatsappIndexRouteImport.update({
  id: '/whatsapp/',
  path: '/whatsapp/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSipExtensionsIndexRoute =
  DashboardSipExtensionsIndexRouteImport.update({
    id: '/sip-extensions/',
    path: '/sip-extensions/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardLeadsIndexRoute = DashboardLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInternalUserIndexRoute =
  DashboardInternalUserIndexRouteImport.update({
    id: '/internal-user/',
    path: '/internal-user/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGsmDevicesIndexRoute =
  DashboardGsmDevicesIndexRouteImport.update({
    id: '/gsm-devices/',
    path: '/gsm-devices/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsIndexRoute = DashboardCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGsmDevicesGsmDeviceIdRoute =
  DashboardGsmDevicesGsmDeviceIdRouteImport.update({
    id: '/gsm-devices/$gsmDeviceId',
    path: '/gsm-devices/$gsmDeviceId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardClientsCreateRoute = DashboardClientsCreateRouteImport.update({
  id: '/clients/create',
  path: '/clients/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsMobileOperatorIndexRoute =
  DashboardSettingsMobileOperatorIndexRouteImport.update({
    id: '/mobile-operator/',
    path: '/mobile-operator/',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsLayoutIndexRoute =
  DashboardSettingsLayoutIndexRouteImport.update({
    id: '/layout/',
    path: '/layout/',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsDefaultPricingIndexRoute =
  DashboardSettingsDefaultPricingIndexRouteImport.update({
    id: '/default-pricing/',
    path: '/default-pricing/',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsAiProviderIndexRoute =
  DashboardSettingsAiProviderIndexRouteImport.update({
    id: '/ai-provider/',
    path: '/ai-provider/',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardClientsClientIdIndexRoute =
  DashboardClientsClientIdIndexRouteImport.update({
    id: '/clients/$clientId/',
    path: '/clients/$clientId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCampaignsCampaignIdIndexRoute =
  DashboardCampaignsCampaignIdIndexRouteImport.update({
    id: '/campaigns/$campaignId/',
    path: '/campaigns/$campaignId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWhatsappSettingIdRoute =
  DashboardWhatsappSettingIdRouteImport.update({
    id: '/whatsapp/setting/$id',
    path: '/whatsapp/setting/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWhatsappDetailsInstanceIdRoute =
  DashboardWhatsappDetailsInstanceIdRouteImport.update({
    id: '/whatsapp/details/$instanceId',
    path: '/whatsapp/details/$instanceId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardClientsClientIdEditRoute =
  DashboardClientsClientIdEditRouteImport.update({
    id: '/clients/$clientId/edit',
    path: '/clients/$clientId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCampaignsCampaignIdAnalyticRoute =
  DashboardCampaignsCampaignIdAnalyticRouteImport.update({
    id: '/campaigns/$campaignId/analytic',
    path: '/campaigns/$campaignId/analytic',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/dashboard/broadcast': typeof DashboardBroadcastRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/create': typeof DashboardClientsCreateRoute
  '/dashboard/gsm-devices/$gsmDeviceId': typeof DashboardGsmDevicesGsmDeviceIdRoute
  '/dashboard/campaigns': typeof DashboardCampaignsIndexRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
  '/dashboard/gsm-devices': typeof DashboardGsmDevicesIndexRoute
  '/dashboard/internal-user': typeof DashboardInternalUserIndexRoute
  '/dashboard/leads': typeof DashboardLeadsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/sip-extensions': typeof DashboardSipExtensionsIndexRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappIndexRoute
  '/dashboard/campaigns/$campaignId/analytic': typeof DashboardCampaignsCampaignIdAnalyticRoute
  '/dashboard/clients/$clientId/edit': typeof DashboardClientsClientIdEditRoute
  '/dashboard/whatsapp/details/$instanceId': typeof DashboardWhatsappDetailsInstanceIdRoute
  '/dashboard/whatsapp/setting/$id': typeof DashboardWhatsappSettingIdRoute
  '/dashboard/campaigns/$campaignId': typeof DashboardCampaignsCampaignIdIndexRoute
  '/dashboard/clients/$clientId': typeof DashboardClientsClientIdIndexRoute
  '/dashboard/settings/ai-provider': typeof DashboardSettingsAiProviderIndexRoute
  '/dashboard/settings/default-pricing': typeof DashboardSettingsDefaultPricingIndexRoute
  '/dashboard/settings/layout': typeof DashboardSettingsLayoutIndexRoute
  '/dashboard/settings/mobile-operator': typeof DashboardSettingsMobileOperatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/dashboard/broadcast': typeof DashboardBroadcastRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/clients/create': typeof DashboardClientsCreateRoute
  '/dashboard/gsm-devices/$gsmDeviceId': typeof DashboardGsmDevicesGsmDeviceIdRoute
  '/dashboard/campaigns': typeof DashboardCampaignsIndexRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
  '/dashboard/gsm-devices': typeof DashboardGsmDevicesIndexRoute
  '/dashboard/internal-user': typeof DashboardInternalUserIndexRoute
  '/dashboard/leads': typeof DashboardLeadsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/sip-extensions': typeof DashboardSipExtensionsIndexRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappIndexRoute
  '/dashboard/campaigns/$campaignId/analytic': typeof DashboardCampaignsCampaignIdAnalyticRoute
  '/dashboard/clients/$clientId/edit': typeof DashboardClientsClientIdEditRoute
  '/dashboard/whatsapp/details/$instanceId': typeof DashboardWhatsappDetailsInstanceIdRoute
  '/dashboard/whatsapp/setting/$id': typeof DashboardWhatsappSettingIdRoute
  '/dashboard/campaigns/$campaignId': typeof DashboardCampaignsCampaignIdIndexRoute
  '/dashboard/clients/$clientId': typeof DashboardClientsClientIdIndexRoute
  '/dashboard/settings/ai-provider': typeof DashboardSettingsAiProviderIndexRoute
  '/dashboard/settings/default-pricing': typeof DashboardSettingsDefaultPricingIndexRoute
  '/dashboard/settings/layout': typeof DashboardSettingsLayoutIndexRoute
  '/dashboard/settings/mobile-operator': typeof DashboardSettingsMobileOperatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/dashboard/broadcast': typeof DashboardBroadcastRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/create': typeof DashboardClientsCreateRoute
  '/dashboard/gsm-devices/$gsmDeviceId': typeof DashboardGsmDevicesGsmDeviceIdRoute
  '/dashboard/campaigns/': typeof DashboardCampaignsIndexRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/gsm-devices/': typeof DashboardGsmDevicesIndexRoute
  '/dashboard/internal-user/': typeof DashboardInternalUserIndexRoute
  '/dashboard/leads/': typeof DashboardLeadsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/sip-extensions/': typeof DashboardSipExtensionsIndexRoute
  '/dashboard/whatsapp/': typeof DashboardWhatsappIndexRoute
  '/dashboard/campaigns/$campaignId/analytic': typeof DashboardCampaignsCampaignIdAnalyticRoute
  '/dashboard/clients/$clientId/edit': typeof DashboardClientsClientIdEditRoute
  '/dashboard/whatsapp/details/$instanceId': typeof DashboardWhatsappDetailsInstanceIdRoute
  '/dashboard/whatsapp/setting/$id': typeof DashboardWhatsappSettingIdRoute
  '/dashboard/campaigns/$campaignId/': typeof DashboardCampaignsCampaignIdIndexRoute
  '/dashboard/clients/$clientId/': typeof DashboardClientsClientIdIndexRoute
  '/dashboard/settings/ai-provider/': typeof DashboardSettingsAiProviderIndexRoute
  '/dashboard/settings/default-pricing/': typeof DashboardSettingsDefaultPricingIndexRoute
  '/dashboard/settings/layout/': typeof DashboardSettingsLayoutIndexRoute
  '/dashboard/settings/mobile-operator/': typeof DashboardSettingsMobileOperatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/verify'
    | '/dashboard/broadcast'
    | '/dashboard/logs'
    | '/dashboard/monitoring'
    | '/dashboard/notifications'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/clients/create'
    | '/dashboard/gsm-devices/$gsmDeviceId'
    | '/dashboard/campaigns'
    | '/dashboard/clients'
    | '/dashboard/gsm-devices'
    | '/dashboard/internal-user'
    | '/dashboard/leads'
    | '/dashboard/settings/'
    | '/dashboard/sip-extensions'
    | '/dashboard/whatsapp'
    | '/dashboard/campaigns/$campaignId/analytic'
    | '/dashboard/clients/$clientId/edit'
    | '/dashboard/whatsapp/details/$instanceId'
    | '/dashboard/whatsapp/setting/$id'
    | '/dashboard/campaigns/$campaignId'
    | '/dashboard/clients/$clientId'
    | '/dashboard/settings/ai-provider'
    | '/dashboard/settings/default-pricing'
    | '/dashboard/settings/layout'
    | '/dashboard/settings/mobile-operator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/verify'
    | '/dashboard/broadcast'
    | '/dashboard/logs'
    | '/dashboard/monitoring'
    | '/dashboard/notifications'
    | '/dashboard/reports'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/clients/create'
    | '/dashboard/gsm-devices/$gsmDeviceId'
    | '/dashboard/campaigns'
    | '/dashboard/clients'
    | '/dashboard/gsm-devices'
    | '/dashboard/internal-user'
    | '/dashboard/leads'
    | '/dashboard/settings'
    | '/dashboard/sip-extensions'
    | '/dashboard/whatsapp'
    | '/dashboard/campaigns/$campaignId/analytic'
    | '/dashboard/clients/$clientId/edit'
    | '/dashboard/whatsapp/details/$instanceId'
    | '/dashboard/whatsapp/setting/$id'
    | '/dashboard/campaigns/$campaignId'
    | '/dashboard/clients/$clientId'
    | '/dashboard/settings/ai-provider'
    | '/dashboard/settings/default-pricing'
    | '/dashboard/settings/layout'
    | '/dashboard/settings/mobile-operator'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/verify'
    | '/dashboard/broadcast'
    | '/dashboard/logs'
    | '/dashboard/monitoring'
    | '/dashboard/notifications'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/clients/create'
    | '/dashboard/gsm-devices/$gsmDeviceId'
    | '/dashboard/campaigns/'
    | '/dashboard/clients/'
    | '/dashboard/gsm-devices/'
    | '/dashboard/internal-user/'
    | '/dashboard/leads/'
    | '/dashboard/settings/'
    | '/dashboard/sip-extensions/'
    | '/dashboard/whatsapp/'
    | '/dashboard/campaigns/$campaignId/analytic'
    | '/dashboard/clients/$clientId/edit'
    | '/dashboard/whatsapp/details/$instanceId'
    | '/dashboard/whatsapp/setting/$id'
    | '/dashboard/campaigns/$campaignId/'
    | '/dashboard/clients/$clientId/'
    | '/dashboard/settings/ai-provider/'
    | '/dashboard/settings/default-pricing/'
    | '/dashboard/settings/layout/'
    | '/dashboard/settings/mobile-operator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/monitoring': {
      id: '/dashboard/monitoring'
      path: '/monitoring'
      fullPath: '/dashboard/monitoring'
      preLoaderRoute: typeof DashboardMonitoringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/broadcast': {
      id: '/dashboard/broadcast'
      path: '/broadcast'
      fullPath: '/dashboard/broadcast'
      preLoaderRoute: typeof DashboardBroadcastRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/whatsapp/': {
      id: '/dashboard/whatsapp/'
      path: '/whatsapp'
      fullPath: '/dashboard/whatsapp'
      preLoaderRoute: typeof DashboardWhatsappIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sip-extensions/': {
      id: '/dashboard/sip-extensions/'
      path: '/sip-extensions'
      fullPath: '/dashboard/sip-extensions'
      preLoaderRoute: typeof DashboardSipExtensionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/leads/': {
      id: '/dashboard/leads/'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/internal-user/': {
      id: '/dashboard/internal-user/'
      path: '/internal-user'
      fullPath: '/dashboard/internal-user'
      preLoaderRoute: typeof DashboardInternalUserIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gsm-devices/': {
      id: '/dashboard/gsm-devices/'
      path: '/gsm-devices'
      fullPath: '/dashboard/gsm-devices'
      preLoaderRoute: typeof DashboardGsmDevicesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/': {
      id: '/dashboard/clients/'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns/': {
      id: '/dashboard/campaigns/'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof DashboardCampaignsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gsm-devices/$gsmDeviceId': {
      id: '/dashboard/gsm-devices/$gsmDeviceId'
      path: '/gsm-devices/$gsmDeviceId'
      fullPath: '/dashboard/gsm-devices/$gsmDeviceId'
      preLoaderRoute: typeof DashboardGsmDevicesGsmDeviceIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/create': {
      id: '/dashboard/clients/create'
      path: '/clients/create'
      fullPath: '/dashboard/clients/create'
      preLoaderRoute: typeof DashboardClientsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/mobile-operator/': {
      id: '/dashboard/settings/mobile-operator/'
      path: '/mobile-operator'
      fullPath: '/dashboard/settings/mobile-operator'
      preLoaderRoute: typeof DashboardSettingsMobileOperatorIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/layout/': {
      id: '/dashboard/settings/layout/'
      path: '/layout'
      fullPath: '/dashboard/settings/layout'
      preLoaderRoute: typeof DashboardSettingsLayoutIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/default-pricing/': {
      id: '/dashboard/settings/default-pricing/'
      path: '/default-pricing'
      fullPath: '/dashboard/settings/default-pricing'
      preLoaderRoute: typeof DashboardSettingsDefaultPricingIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/ai-provider/': {
      id: '/dashboard/settings/ai-provider/'
      path: '/ai-provider'
      fullPath: '/dashboard/settings/ai-provider'
      preLoaderRoute: typeof DashboardSettingsAiProviderIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/clients/$clientId/': {
      id: '/dashboard/clients/$clientId/'
      path: '/clients/$clientId'
      fullPath: '/dashboard/clients/$clientId'
      preLoaderRoute: typeof DashboardClientsClientIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns/$campaignId/': {
      id: '/dashboard/campaigns/$campaignId/'
      path: '/campaigns/$campaignId'
      fullPath: '/dashboard/campaigns/$campaignId'
      preLoaderRoute: typeof DashboardCampaignsCampaignIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/whatsapp/setting/$id': {
      id: '/dashboard/whatsapp/setting/$id'
      path: '/whatsapp/setting/$id'
      fullPath: '/dashboard/whatsapp/setting/$id'
      preLoaderRoute: typeof DashboardWhatsappSettingIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/whatsapp/details/$instanceId': {
      id: '/dashboard/whatsapp/details/$instanceId'
      path: '/whatsapp/details/$instanceId'
      fullPath: '/dashboard/whatsapp/details/$instanceId'
      preLoaderRoute: typeof DashboardWhatsappDetailsInstanceIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/$clientId/edit': {
      id: '/dashboard/clients/$clientId/edit'
      path: '/clients/$clientId/edit'
      fullPath: '/dashboard/clients/$clientId/edit'
      preLoaderRoute: typeof DashboardClientsClientIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns/$campaignId/analytic': {
      id: '/dashboard/campaigns/$campaignId/analytic'
      path: '/campaigns/$campaignId/analytic'
      fullPath: '/dashboard/campaigns/$campaignId/analytic'
      preLoaderRoute: typeof DashboardCampaignsCampaignIdAnalyticRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardSettingsRouteChildren {
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardSettingsAiProviderIndexRoute: typeof DashboardSettingsAiProviderIndexRoute
  DashboardSettingsDefaultPricingIndexRoute: typeof DashboardSettingsDefaultPricingIndexRoute
  DashboardSettingsLayoutIndexRoute: typeof DashboardSettingsLayoutIndexRoute
  DashboardSettingsMobileOperatorIndexRoute: typeof DashboardSettingsMobileOperatorIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardSettingsAiProviderIndexRoute: DashboardSettingsAiProviderIndexRoute,
  DashboardSettingsDefaultPricingIndexRoute:
    DashboardSettingsDefaultPricingIndexRoute,
  DashboardSettingsLayoutIndexRoute: DashboardSettingsLayoutIndexRoute,
  DashboardSettingsMobileOperatorIndexRoute:
    DashboardSettingsMobileOperatorIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardBroadcastRoute: typeof DashboardBroadcastRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardMonitoringRoute: typeof DashboardMonitoringRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClientsCreateRoute: typeof DashboardClientsCreateRoute
  DashboardGsmDevicesGsmDeviceIdRoute: typeof DashboardGsmDevicesGsmDeviceIdRoute
  DashboardCampaignsIndexRoute: typeof DashboardCampaignsIndexRoute
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
  DashboardGsmDevicesIndexRoute: typeof DashboardGsmDevicesIndexRoute
  DashboardInternalUserIndexRoute: typeof DashboardInternalUserIndexRoute
  DashboardLeadsIndexRoute: typeof DashboardLeadsIndexRoute
  DashboardSipExtensionsIndexRoute: typeof DashboardSipExtensionsIndexRoute
  DashboardWhatsappIndexRoute: typeof DashboardWhatsappIndexRoute
  DashboardCampaignsCampaignIdAnalyticRoute: typeof DashboardCampaignsCampaignIdAnalyticRoute
  DashboardClientsClientIdEditRoute: typeof DashboardClientsClientIdEditRoute
  DashboardWhatsappDetailsInstanceIdRoute: typeof DashboardWhatsappDetailsInstanceIdRoute
  DashboardWhatsappSettingIdRoute: typeof DashboardWhatsappSettingIdRoute
  DashboardCampaignsCampaignIdIndexRoute: typeof DashboardCampaignsCampaignIdIndexRoute
  DashboardClientsClientIdIndexRoute: typeof DashboardClientsClientIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBroadcastRoute: DashboardBroadcastRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardMonitoringRoute: DashboardMonitoringRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClientsCreateRoute: DashboardClientsCreateRoute,
  DashboardGsmDevicesGsmDeviceIdRoute: DashboardGsmDevicesGsmDeviceIdRoute,
  DashboardCampaignsIndexRoute: DashboardCampaignsIndexRoute,
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
  DashboardGsmDevicesIndexRoute: DashboardGsmDevicesIndexRoute,
  DashboardInternalUserIndexRoute: DashboardInternalUserIndexRoute,
  DashboardLeadsIndexRoute: DashboardLeadsIndexRoute,
  DashboardSipExtensionsIndexRoute: DashboardSipExtensionsIndexRoute,
  DashboardWhatsappIndexRoute: DashboardWhatsappIndexRoute,
  DashboardCampaignsCampaignIdAnalyticRoute:
    DashboardCampaignsCampaignIdAnalyticRoute,
  DashboardClientsClientIdEditRoute: DashboardClientsClientIdEditRoute,
  DashboardWhatsappDetailsInstanceIdRoute:
    DashboardWhatsappDetailsInstanceIdRoute,
  DashboardWhatsappSettingIdRoute: DashboardWhatsappSettingIdRoute,
  DashboardCampaignsCampaignIdIndexRoute:
    DashboardCampaignsCampaignIdIndexRoute,
  DashboardClientsClientIdIndexRoute: DashboardClientsClientIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
